#!/usr/bin/env python3

"""
Deploy rules/*.kql to Microsoft Sentinel as Scheduled Analytics Rules.

Requirements:
    - Azure CLI installed
    - az login completed
    - Permission to create/update Sentinel Analytics Rules

Example dry run:
    python3 deploy/deploy_analytics_rules.py \
        --subscription "$(az account show --query id -o tsv)" \
        --resource-group rg-soc-lab \
        --workspace law-soc \
        --dry-run

Example deployment:
    python3 deploy/deploy_analytics_rules.py \
        --subscription "$(az account show --query id -o tsv)" \
        --resource-group rg-soc-lab \
        --workspace law-soc
"""

import argparse
import json
import re
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path


API_VERSION = "2023-02-01"


def get_token():
    """Get an Azure Resource Manager access token using Azure CLI."""
    result = subprocess.run(
        [
            "az",
            "account",
            "get-access-token",
            "--resource",
            "https://management.azure.com",
            "--query",
            "accessToken",
            "-o",
            "tsv",
        ],
        capture_output=True,
        text=True,
        check=True,
    )

    token = result.stdout.strip()

    if not token:
        raise RuntimeError("Azure CLI returned an empty access token.")

    return token


def arm_put(url, token, body):
    """Create or update an Azure Resource Manager resource."""
    request = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="PUT",
    )

    try:
        with urllib.request.urlopen(request) as response:
            return response.status

    except urllib.error.HTTPError as error:
        response_body = error.read().decode("utf-8", errors="replace")
        print(f"  FAIL: HTTP {error.code}: {response_body[:1000]}")
        return error.code


def parse_meta(path):
    """
    Parse metadata generated by scripts/generate_50_rules.py.

    Expected format:

        // METADATA-START
        // id: ...
        // name: ...
        // severity: ...
        // tactics: ...
        // techniques: ...
        // METADATA-END
    """

    text = path.read_text(encoding="utf-8")

    def get_field(field, default):
        match = re.search(
            rf"^// {re.escape(field)}:\s*(.+?)\s*$",
            text,
            re.MULTILINE,
        )

        return match.group(1).strip() if match else default

    rule_id = get_field("id", path.stem)
    name = get_field("name", path.stem)
    severity = get_field("severity", "Medium")
    tactics = get_field("tactics", "Unknown")
    techniques = get_field("techniques", "Unknown")

    return {
        "id": rule_id,
        "name": name,
        "severity": severity,
        "tactics": tactics,
        "techniques": techniques,
    }, text


def build_rule_body(metadata, query, workspace):
    """Build the Microsoft Sentinel Scheduled Analytics Rule payload."""

    severity = metadata["severity"].capitalize()

    allowed_severities = {
        "Informational",
        "Low",
        "Medium",
        "High",
        "Critical",
    }

    if severity not in allowed_severities:
        severity = "Medium"

    description = (
        f"MITRE tactics: {metadata['tactics']} | "
        f"MITRE techniques: {metadata['techniques']} | "
        f"Source workspace: {workspace}"
    )

    return {
        "kind": "Scheduled",
        "properties": {
            "displayName": f"[{metadata['id']}] {metadata['name']}",
            "description": description,
            "severity": severity,
            "enabled": True,
            "query": query,
            "queryFrequency": "PT5M",
            "queryPeriod": "PT1H",
            "triggerOperator": "GreaterThan",
            "triggerThreshold": 0,
            "suppressionDuration": "PT1H",
            "suppressionEnabled": False,
            "eventGroupingSettings": {
                "aggregationKind": "AlertPerResult"
            },
        },
    }


def main():
    parser = argparse.ArgumentParser(
        description="Deploy KQL rules to Microsoft Sentinel."
    )

    parser.add_argument(
        "--subscription",
        required=True,
        help="Azure subscription ID",
    )

    parser.add_argument(
        "--resource-group",
        required=True,
        help="Azure resource group containing the Log Analytics workspace",
    )

    parser.add_argument(
        "--workspace",
        required=True,
        help="Log Analytics workspace name",
    )

    parser.add_argument(
        "--rules-dir",
        default="rules",
        help="Directory containing .kql files",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and print rules without deploying them",
    )

    args = parser.parse_args()

    rules_dir = Path(args.rules_dir)

    if not rules_dir.exists():
        raise SystemExit(f"Rules directory does not exist: {rules_dir}")

    rule_files = sorted(rules_dir.glob("*.kql"))

    if not rule_files:
        raise SystemExit(f"No .kql files found in {rules_dir}")

    print(f"Found {len(rule_files)} KQL rules.")

    if args.dry_run:
        print("DRY RUN: no Sentinel resources will be changed.")
        token = None
    else:
        token = get_token()

    base_url = (
        "https://management.azure.com/"
        f"subscriptions/{args.subscription}/"
        f"resourceGroups/{args.resource_group}/"
        "providers/Microsoft.OperationalInsights/"
        f"workspaces/{args.workspace}/"
        "providers/Microsoft.SecurityInsights/"
        "alertRules/"
    )

    success = 0
    failed = 0

    for rule_file in rule_files:
        metadata, query = parse_meta(rule_file)

        rule_id = metadata["id"]
        name = metadata["name"]
        severity = metadata["severity"]

        if args.dry_run:
            print(
                f"[DRY] {rule_id} | {name} | "
                f"severity={severity} | "
                f"tactics={metadata['tactics']} | "
                f"techniques={metadata['techniques']}"
            )
            success += 1
            continue

        body = build_rule_body(
            metadata,
            query,
            args.workspace,
        )

        url = f"{base_url}{rule_id}?api-version={API_VERSION}"

        status = arm_put(
            url,
            token,
            body,
        )

        print(
            f"{rule_id} {name}: HTTP {status}"
        )

        if status in (200, 201):
            success += 1
        else:
            failed += 1

        time.sleep(0.3)

    print()
    print("=" * 60)
    print("DEPLOYMENT SUMMARY")
    print("=" * 60)
    print(f"Rules found: {len(rule_files)}")
    print(f"Successful:  {success}")
    print(f"Failed:      {failed}")

    if args.dry_run:
        print("Mode:         DRY RUN")
    else:
        print("Mode:         DEPLOYMENT")

    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
